### ISSUE TITLE
Can't get hbbs and hbbr to start

### ISSUE THREAD

**Issue by EBS-DarkD** [rustdesk/rustdesk-server#143]
I've just built a Debian 11 server to host a RustDesk server instance.
Followed the instructions here - https://rustdesk.com/docs/en/self-host/install/#step-1--download-server-side-software-programs
Not running through docker so I used the install.sh and have a "go http file server" running on the server with a Linux script and Windows powershell

I have installed pm2 but it doesn't matter if I try start hbbs from the cmd line or via pm2, I get the same issue

****@****:/opt/rustdesk$ ./hbbs -r *************
[2022-11-15 14:44:54.047047 +03:00] INFO [src/common.rs:110] Private key comes from id_ed25519
[2022-11-15 14:44:54.047084 +03:00] INFO [src/peer.rs:82] DB_URL=./db_v2.sqlite3
[2022-11-15 14:44:54.049170 +03:00] INFO [src/rendezvous_server.rs:98] serial=0
[2022-11-15 14:44:54.049186 +03:00] INFO [src/common.rs:40] rendezvous-servers=[]
[2022-11-15 14:44:54.049192 +03:00] INFO [src/rendezvous_server.rs:100] Listening on tcp/udp 0.0.0.0:21116
[2022-11-15 14:44:54.049197 +03:00] INFO [src/rendezvous_server.rs:101] Listening on tcp 0.0.0.0:21115, extra port for NAT test
[2022-11-15 14:44:54.049201 +03:00] INFO [src/rendezvous_server.rs:102] Listening on websocket 0.0.0.0:21118
[2022-11-15 14:44:54.049237 +03:00] INFO [libs/hbb_common/src/udp.rs:35] Receive buf size of udp 0.0.0.0:21116: Ok(212992)
Error: Address in use (os error 98)

I'm getting similar errors when I start hbbs. Doesn't matter if I run as my user or sudo or root!

Anyone advise on what i've done wrong?

**Comment by EBS-DarkD** [comment]
Ok, I've figured out what's going on. Please ignore this

**Comment by li-dianzheng** [comment]
I have encountered the same problem as you, I would like to ask how you solved it?

**Comment by paspo** [comment]
well...
` Error: Address in use (os error 98)` is self-explanatory...

He was probably trying to use a port already used by another process.

**Comment by duczz** [comment]
I have the same Error, which Port should be used in this case? 21117 is default
I need only the -k _ Parameter added

**Comment by paspo** [comment]
> I have the same Error, which Port should be used in this case? 21117 is default I need only the -k _ Parameter added

If you have the same error, most probably is because of the same issue.
If it says that the port 21117 is already in use, you should ask the person who manages that machine (you?) who's using that port, or ask for a free port range you can use.
There's no way anyone different than the person who manages that machine (you?) know what's running on that machine.

If that person is you, you should invest more time in being fluent with containers; maybe start with a webgui like [portainer](https://www.portainer.io/), which can make things easier.

If you're not using containers, the cause is the same (another process is using that port), but the context is different.
This command should give you a hint:

```bash
netstat -pant | grep 21117
```

**Comment by duczz** [comment]
hbbr use this port.
![image](https://user-images.githubusercontent.com/25475385/214036320-27746939-5cf2-4887-b5e8-8eb75ea9c1b6.png)

**Comment by Qhilm** [comment]
Same here, on 1.1.11, hbbs is complaining it cannot use 21117, and `netstat -pant | grep 21117` shows it's hbbr who is using it.
