### ISSUE TITLE
Copy and paste

### ISSUE THREAD

**Issue by raiduarte** [rustdesk/rustdesk-server#146]
This is the place for generic questions. Please stay on topic and be polite.

**Notes**
 - Please write in english only. If you provide some images in different languages, you're required to write a translation in english.
 - In any case, **NEVER** put here the content if your `id_ed25519` file
May I copy a file that is on my PC and tranfer it by paste to the other PC?

**Comment by paspo** [comment]
I hate to be harsh, but this issue is wrong in so many ways... 

# Formatting and presentation

It's just a good idea to write something "easy to read" if you want somebody to actually read it. 
When I saw the issue, it was clear that you didn't take the 3 seconds needed to remove the "template" text, and buried your question in the process.
There's a "preview" button on github, in practically every editing inputs.
How can you expect someone to waste his free time (we're almost all volunteers here) if you don't take the time needed to make the thing easy?
If this issue is not worth 10 more seconds of your time spent editing, it's definitely not worth 10 seconds of anybody time.

# Choosing the right repository

On the Rustdesk project, there are 3 main repositories:

- [the rustdesk client](https://github.com/rustdesk/rustdesk)
- [the rustdesk server](https://github.com/rustdesk/rustdesk-server) (this repository)
- [documentation](https://github.com/rustdesk/doc.rustdesk.com)

You opened an issue on the server repository that was meant to be on the client repository.
Again, wasting time.

# Your question

This question is so simple to be checked by yourself that honestly I don't think it deserves an issue. 
You start a session and try. This is in fact what I'm going to do to answer your question.

# Your answer

Copy and paste is for plain text only, even images can't be copy/pasted through a rustdesk session.
But you have other options: you can transfer whole files, you can redirect a port (let's say you redirect SMB and use this protocol to transfer the file),  or you can use a cloud-something system (nextcloud, projectsend, wormhole, firefox send...) to share a link (which you can copy paste).

# Conclusion

Please @rustdesk close this issue as "not relevant". 
Let's bookmark this issue for future reference: I wasted 15 minutes in writing this so nobody has to.

**Comment by rustdesk** [comment]
> Let's bookmark this issue for future reference: I wasted 15 minutes in writing this so nobody has to.

So sorry for this.
