### ISSUE TITLE
Linux watchdog is faulty

### ISSUE THREAD

**Issue by attikov** [rustdesk/rustdesk-server#216]
### Bug Description

 systemd[1]: rustdeskrelay.service: Scheduled restart job, restart counter is at 738978.

how can I stop this? I have a 500M+ log full of this, the server runs fine, this schduler is faulty.

### How to Reproduce

Install it on a recent debian

### Expected Behavior

no excessive logs are generated

### Operating system(s) on local side and remote side

Debian

### RustDesk Version(s) on local side and remote side

?

### Screenshots

![image](https://user-images.githubusercontent.com/17452773/224480354-e81699fb-e922-432f-aadb-2ad70cdfd10c.png)

**Comment by paspo** [comment]
I just installed a fresh debian 11 (amd64) and latest .deb packages (1.1.7).


> I have no ide what those are but both services was pointing to the same binary

Services are defined in `/usr/lib/systemd/system/rustdesk-hbbr.service` and `/usr/lib/systemd/system/rustdesk-hbbs.service`. If you look at the content of these files, the binary (`ExecStart=` line) are different.


The service configuration tells systemd to restart the services after 10 secs if the service dies. If one of the two services dies, you should take a look in the logs to figure out why. The logs are placed in `/var/log/rustdesk/`, splitted by service and by type (general log and error log).

I noticed that the service you mention is called `rustdeskrelay.service` which is strange, because the service definition from the .deb packages are called `rustdesk-hbbr.service` and `rustdesk-hbbs.service`.
You should definitely check why is that.

**Comment by attikov** [comment]
I have to ask how do you install it as there is no rustdesk-hbbr / hbbs service after installing it like the how-to suggests

**Comment by attikov** [comment]
@paspo thx man, your notes helped me to spot the problem, I had indeed one rustdesk-hbbr.service left in systemd and the 2 other ones. So the 2 relay services were fighting for the ports. I can't imagine how I managed it back in the days.

thank you

**Comment by paspo** [comment]
> I have to ask how do you install it as there is no rustdesk-hbbr / hbbs service after installing it like the how-to suggests

In the [releases section](https://github.com/rustdesk/rustdesk-server/releases) you can find latest .deb files.
You download on the target machine, then:

```bash
apt install ./rustdesk-server-hbbr_1.1.7_amd64.deb ./rustdesk-server-hbbs_1.1.7_amd64.deb
```

**Comment by attikov** [comment]
> apt install ./rustdesk-server-hbbr_1.1.7_amd64.deb ./rustdesk-server-hbbs_1.1.7_amd64.deb

I see, I downloaded the installer mentioned in the Howto/Installation. Maybe I tried dpkg before tat, that's why I had 2 different servies.

@rustdesk why are there 2 different intallers? At least the result (service names) should be the same after installation.
