### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by vsviridov** [rustdesk/rustdesk-server#38]
Currently the server does not seem to listen on IPv6 hosts, only on IPv4.

The client however will attempt to connect to IPv6 if the domain name is used and both A and AAAA records exist. Either prevent the client from attempting to connect via IPv6 or make the server listen on IPv6 hosts as well...

**Comment by paspo** [comment]
At the moment, IPv6 is not supported by either hbbs or hbbr.

The direction of the project, at least on the client side, is towards IPv6; maybe we should enable it server-side also.

**Comment by rustdesk** [comment]
https://twitter.com/rustdesk/status/1538758459373813760

**Comment by gccgomes** [comment]
Hi there, could I open a new branch to test some modifications to support ipv6 on hbbr and hbbs ?

**Comment by rustdesk** [comment]
> Hi there, could I open a new branch to test some modifications to support ipv6 on hbbr and hbbs ?

Of course. I created ipv6 branch a moment ago.

**Comment by Husky110** [comment]
Just to add to this: In Germany we have the problem that most ISPs do not support IPv4 anymore. In fact - most IPv4-traffic is routed via a tunnel (like IPv6 used to be) and when you selfhost stuff behind a private internet-connection the connector has to use IPv6 aswell. I've tried it with the help of the comments in [#835](https://github.com/rustdesk/rustdesk/issues/835) and it works fine inside my LAN when I use the IPv4-address of my machine. Using my DynDNS-entry: well... nope... :) So any help here would be really appreciated.

**Comment by konwin** [comment]
> most ISPs 
"most" is not true. It is mainly cable-providers. Are you using the supplied router/modem? In most regions you get an IPv4 (unfortunaltey only, no DS) if you use their device in bridge-mode and connect a "real" router behind that!?

**Comment by Husky110** [comment]
@konwin - I'm using 1&1 with a FritzBox that I bought on amazon... :) I've been told Vodafone does the same and even if it's not "most ISPs" at the moment, it will be eventually, since all of them are switching on a global scale. In my oppinion you can't deploy any software anymore that does not support it out of the box, without facing massive criticise. But that is just my oppinion. :)

**Comment by JeGr** [comment]
> "most" is not true. It is mainly cable-providers. Are you using the supplied router/modem? In most regions you get an IPv4 (unfortunaltey only, no DS) if you use their device in bridge-mode and connect a "real" router behind that!?

That is irrelevant and not the point. Fact is, we have 2022 and every new ISP everywhere popping up will not have vast amounts of IPv4 space because there is no big ranges left. So most new providers WILL use DS-lilte or some kind of NAT64 traversal and will always try to safe IPv4s for either paying business customers or special use cases. Even the bigger/older players try constantly to slip in changes back to DSlite after contract changes to clear up "unused" or "unneccesary" IP4s. It simply is a fact that going forward most home/small business users will see lines with no real IPv4 attached anymore. Ignoring or downplaying IPv6 today makes no sense at all. The server parts definetly need IPv6 support to be reasonably useful.
Coming from a datacenter perspective I'd really like to test drive rustdesk, but our servers and services are dual stacked at least and some even v6 only so hopefully that will be adressed sooner than later. :)

**Comment by Avey777** [comment]
ipv6 support is hoped to be online as soon as possible

**Comment by bt90** [comment]
Seems to be fixed according to the latest release notes.

**Comment by bigretromike** [comment]
Looks like ipv6 was added to server: https://github.com/rustdesk/rustdesk-server/tree/1.1.7 @rustdesk

**Comment by loxK** [comment]
No, it still isn't working over ipv6, clients cannot connect
