### ISSUE TITLE
Question: What is the API Server and how do I run it off-grid

### ISSUE THREAD

**Issue by Silberling** [rustdesk/rustdesk-server#42]
Hi,

In the settings i can specify an API server and a key, too.
Searching didn't yield anything useful and There seems to be nothing inside the docker container, in the docs and no repo. But how can I run my own API server and take this whole thing behind a firewall with no internet connection?

Thanks for help!

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/wiki/FAQ#change-id-addressbookapilogin-and-web-console

**Comment by paspo** [comment]
The API part of the question has been answered by @rustdesk.

I can help with your use case.

Just a recap:

- you have a local network from which all the client devices can't go outside (or they have some strong limits like a small whitelist of hosts/ports)
- you need to have rustdesk running without outside comunication, to do helpdesk stuff (in this scenario, most likely you're using VNC for that now)
- in fact, you don't even need a relay server (hbbr) if the hosts can communicate with each other (because they're on the same network or because the firewall allows it)

You can do this in two ways:

* you install the server part on a VM/container somewhere inside your network and make it reachable from all the hosts
* you allow direct IP connection on the client itself, so you don't even need a server

**Comment by paspo** [comment]
Now I added a third VM to the mix, with docker, docker-compose, and the rustdesk-server-s6 docker image.

I entered the IP address of this VM as the relay in both clients and immediately got an ID for each VM.

I allowed **encrypted only** connection to the server and checked that the clients couldn't connect without the public key.

Then I added the correct public key to both client and the connection worked, via the internal server.

All of that, on a separate network, not connected to internet or any other gateway.

So this confirms the other scenario.

**Comment by paspo** [comment]
Now we wait for @Silberling feedback, hope this helps.

**Comment by Silberling** [comment]
Hey @paspo,

Thanks for reminding me this is still open.
And thanks for the technical explanation and I really appreciate your time and work you spend in answering this.

But I was only interested in the technical background of the API Server and infrastructure integration.
* What this will be used for?
* How does the API look like?
* What features does it provide?
* And as a professional developer and administrator (and private person in case of my github account), how can I tinker with it?
* What benefit except for off-grid usage does it provide for customers?
* If they're gonna go make a pro version will the customers accept a price if Microsofts "Quick Assist" is free and already established? (Can hear customers counterargument already ;-))

May 31 2022: "It is temporarily removed, because we are still thinking about how to do our RustDesk Server Pro version for advanced business users."
Source: https://github.com/rustdesk/rustdesk/issues/509

I just sit here and wait and keep an eye on that project and wait for pro and prices.

**Comment by rustdesk** [comment]
Nothing special, just something you can see from AnyDesk/Parsec self-hosting or enterprise account.
