### ISSUE TITLE
missing rustdesk/rustdesk-server-s6 from Docker Hub

### ISSUE THREAD

**Issue by tethryus** [rustdesk/rustdesk-server#49]
Hello, I am trying to deploy any of the S6-overlay based images and they are not present in Docker Hub.

**Comment by paspo** [comment]
We just implemented the automated build (see this PR https://github.com/rustdesk/rustdesk-server/pull/43), but the real build (which is triggered by a git tag) hasn't happened yet. 

If you need to test it ASAP, all I can offer are the images I made during the develop of that PR. 

```bash 
docker pull paspo/rustdesk-server
```

Just use that image instead of the official one, and switch back to the official one as soon as the new version gets released.

**Comment by paspo** [comment]
can you please test if 

`docker pull paspo/rustdesk-server:latest-arm64v8`

is working for you?

BTW: it's my bad... I'm fixing it

**Comment by paspo** [comment]
https://github.com/rustdesk/rustdesk-server/pull/50 will fix this

**Comment by tethryus** [comment]
Thank you very much, I will use the provided image and let you know how it works.

**Comment by tethryus** [comment]
I am getting this error on: paspo/rustdesk-server:latest

`
/package/admin/s6-overlay/libexec/preinit: notice: /var/run is not a symlink to /run, fixing it
s6-rmrf: fatal: unable to remove /var/run: Read-only file system
s6-overlay-suexec: fatal: child failed with exit code 111
`

**Comment by paspo** [comment]
@tethryus what architecture are you on?

are you using `docker-compose` or are you using a `docker run ...` command?

**Comment by tethryus** [comment]
@paspo I am trying to deploy it to kubernetes, using helm on amd64

**Comment by paspo** [comment]
@tethryus on second tought, it's better to open a new issue
