### ISSUE TITLE
Benefit of hosted rustdesk and what happen if my rustdest server offline?

### ISSUE THREAD

**Issue by vyncusp** [rustdesk/rustdesk-server#75]
Hi,

Can someone explain to me what is the benefit of hosted rustdesk and what happen if my rustdest server offline?

**Comment by paspo** [comment]
The main benefit is that it allows you to have full control of all the communications between clients. With encryption enabled, you're pretty sure that nobody else is "listening" in any way.

That said, it also means that you're in charge of maintaining the service alive, so if the server is offline, only direct IP connection is working (if enabled).

With other commercial solutions, the "solution provider" (TeamViewer, AnyDesk, ...) knows when (and where, due to IP address location) you connect from your PC to another PC, and keeps a log. That's the minimum which is known for sure. Connection between the PC and the server can be encrypted or not, but it is "readable" from the server. And you have no control over that.

I can also present the fact that my TeamViewer account gets A LOT of "forgotten password" requests, and this is usual if this is part of your job: an account can grant access to hundreds of PCs/servers. Thanks to strong passwords, IP filtering and MFA, nobody got access to my account. Except TeamViewer itself.

The day TeamViewer gets hacked, we're all screwed. And there's nothing we can do about it.

rustdesk-server is open-source (a lot of eyes are vetting the code) which means real security instead of security-through-obscurity; also if the server gets compromised, I can fix it.

**Comment by vyncusp** [comment]
Is there possible to make automatic setting in client side if my server down it will switch to rustdesk server?

**Comment by Enrico204** [comment]
> Is there possible to make automatic setting in client side if my server down it will switch to rustdesk server?

That is a security and confidentiality issue. I strongly suggest to **not** do that.

Depending on your threat model, you have different options: if you need reliability and security/confidentiality, you may have redundant server / services (DNS round robin, load balancer, anycast, etc). If security and confidentiality are not your priority in your threat model, you may trust the RustDesk owners.
